config/routes.rb
Rails.application.routes.draw do
  get 'user_detail/edit'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'toppages#index'
  resources :toppages, only: [:index]  do
    collection do 
      get 'search'
    end
  end
  resources :users do
    member do
      get :logout
      get :sms_confirmation
      get :address
      get :credit_card
      post :address
      post :credit_card
      get :finish
      get :credit_card_registration
    end
    resources :items, only: [:index, :new, :edit]
  end
  resources :items, except: [:index, :new, :edit] do
    resources :deals do
      collection do
        post 'purchase'
      end
    end
  end
  resources :items, except: [:index, :new, :edit]
  resources :item_images, only: [:new,:create, :destroy]
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end 
  resources :card, only: [:new, :show] do
    collection do
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  has_one_attached :image
  has_one :user_detail
  has_one :card
  accepts_nested_attributes_for :user_detail
  has_many :items
  has_many :deals

  validates :nickname, presence: true, length: {maximum: 20}
  validates :password, presence: true, length: {minimum: 7, maximum: 128},  format: {with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{7,128}+\z/i}

  def self.find_auth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.nickname = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image 
      
      # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @user = User.find_auth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #after_sign_in_path_forと同じパス
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to signup_registration_path
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # prepend_before_action :check_captcha, only: [:create]

  # GET /resource/sign_up
  def new
    super
    @user = User.new
  end

  # POST /resource
  def create
    super
    # binding.pry
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    sms_confirmation_user_path(current_user.id)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  # end

  private
    def check_captcha
      unless verify_recaptcha
        self.resource = resource_class.new sign_up_params
        resource.validate # Look for any other validation errors besides Recaptcha
        set_minimum_password_length
        respond_with resource
      end 
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # prepend_before_action :check_captcha, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  private
    def check_captcha
      unless verify_recaptcha
        self.resource = resource_class.new sign_in_params
        resource.validate # Look for any other validation errors besides Recaptcha
        set_minimum_password_length
        respond_with resource
      end 
    end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :call_categories
  before_action :card_check, only: :credit_card
  # before_action :move_to_signup, except: [:new]
  skip_before_action :authenticate_user!, only: [:new]
  def index

  end

  def new
    
  end

  def create
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    
  end

  def logout
    
  end

  def sms_confirmation
    
  end

  def credit_card
  end


  def address
    @regions = Region.all
  end
  
  def credit_card_registration
    
  end

  def finish

  end

  private
  def call_categories
    @categories = Category.all
  end

  def card_check
    if current_user.card.present?
      redirect_to card_path
    end
  end
  # def move_to_signup
  #   redirect_to new_user_session_path unless authenticate_user?
  # end

end

app/views/users/address.html.haml
!!!
= render partial: 'layouts/user_registration_status_bar'
.single-main
  .single-content
    .single-content-top
      住所入力
    .single-content-main
      .s-content-main
      = fields_for :user_detail, UserDetail.new do |f|
        .form__box-address
          .form-group
            %label お名前
            %span.form-require 必須
            = f.text_field :family_name_kanji, placeholder: "例) メルカリ", class: "input-address-name"
            = f.text_field :first_name_kanji, placeholder: "例) 太郎", class: "input-address-name-under"
        .form__box-address
          .form-group
            %label お名前カナ
            %span.form-require 必須
            = f.text_field :family_name_kana, placeholder: "例) メルカリ", class: "input-address-name"
            = f.text_field :first_name_kana, placeholder: "例) タロウ", class: "input-address-name-under"
      = fields_for :address, Address.new do |i|
        .form__box-address
          .form-group
            %label 郵便番号
            %span.form-require 必須
            = i.text_field :address, placeholder: "例) 123-4567", class: "input-default"
        .form__box-address
          .form-group
            %label 都道府県
            %span.form-require 必須
            %select.input-default
              %option{selected:"selected"} ---
              -@regions.each do |region|
                %option{value: region.id} #{region.name}
        .form__box-address
          .form-group
            %label 市区町村
            %span.form-require 必須
            = i.text_field :address, placeholder: "例) メルカリ町メルカリ区", class: "input-default"
        .form__box-address
          .form-group
            %label 番地
            %span.form-require 必須
            = i.text_field :address, placeholder: "例) メルカリ5-1-1", class: "input-default"
        .form__box-address
          .form-group
            %label 建物名
            %span.form-require-ninni 任意
            = i.text_field :address, placeholder: "例) メルカリ太郎", class: "input-default"
        .form__box-address
          .form-group
            %label 電話番号
            %span.form-require-ninni 任意
            = i.text_field :address, placeholder: "例) メルカリ太郎", class: "input-default"
        .form-group
          -# = f.submit "次へ進む", class: "btn-default btn-red-address"
          = link_to credit_card_registration_user_path(current_user.id), {class: "btn-default btn-red-address", style: "display:block;text-align:center;"} do
            次へ進む

= render partial: '/shared/footers', locals: { categories: @categories }

app/views/users/credit_card.html.haml
= render partial: '/shared/headers', locals: { categories: @categories }
/////////////////////////////////

.credit_card_main
  .credit_card_main__left
    .credit_card_main__left__box
    =render partial:'/shared/side_bar'
  .credit_card_main__right
    .credit_card_main__right__box
      .credit_card_main__right__box__top
        支払い方法
      .credit_card_main__right__box__bottom
        .credit
          クレジットカード一覧
        .add-credit
          =link_to new_card_path(current_user.id)do
            = fa_icon "credit-card"
            クレジットカードを追加する
      .credit_card_main__right__box__2
        支払い方法について
        = fa_icon "angle-right" 

///////////////////////////////////

/////////////////////
//ここはフッター

= render partial: '/shared/footer2'

app/views/users/credit_card_registration.html.haml
!!!
= render partial: 'layouts/user_registration_status_bar'
%main.main
  %section.contents
    .payment__title 
      支払い方法
    .form__box
      .form-group.card-number
        %label{for:"card_number"} カード番号
        %span.form-require 必須
        %input.input-default.for-card{placeholder: "半角数字のみ"}


    .form-group
      .card-images
        = image_tag(image_url('visa.png'))
        = image_tag(image_url('mastercard.png'))
        = image_tag(image_url('saisoncard.png'))
        = image_tag(image_url('jcb.png'))
        = image_tag(image_url('americanexpress.png'))
        = image_tag(image_url('dinersclub.png'))
        = image_tag(image_url('discover.png'))

    .form__box.card-details
      .form-group
        %label{for:"expires"} 有効期限
        %span.form-require 必須
        %select{name: "month-year", class: "month-year-month"}
          %option{:value => ""} -
          %option{:value => "1"} 1
          %option{:value => "2"} 2
          %option{:value => "3"} 3
          %option{:value => "4"} 4
          %option{:value => "5"} 5
          %option{:value => "6"} 6
          %option{:value => "7"} 7
          %option{:value => "8"} 8
          %option{:value => "9"} 9
          %option{:value => "10"} 10
          %option{:value => "11"} 11
          %option{:value => "12"} 12
        %span 月
        %select{:name => "year", class: "month-year-year"}
          %option{:value => ""} -
          %option{:value => "2019"} 2019
          %option{:value => "2020"} 2020
          %option{:value => "2021"} 2021
          %option{:value => "2022"} 2022
          %option{:value => "2023"} 2023
          %option{:value => "2024"} 2024
          %option{:value => "2025"} 2025
          %option{:value => "2026"} 2026
          %option{:value => "2027"} 2027
          %option{:value => "2028"} 2028
        %span 年
    .security-box
      .form__box
        .form-group.security-code
          %label{for:"security_code"} セキュリティコード
          %span.form-require 必須
          %input.input-default.fourtothree{placeholder: "カード背面4桁もしくは3桁の番号"}

    .question
      = link_to "#" do
        = fa_icon "question-circle"
      %a カード裏面の番号とは？
          
    .form-group
      = link_to finish_user_path(current_user.id), {class: "btn-default btn-red-address", style: "display:block;text-align:center;"} do
        次へ進む


  = render partial: '/shared/footers', locals: { categories: @categories }

app/views/users/edit.html.haml
-# 検索窓やカテゴリーのドロップダウンメニューがあるheader
= render partial: "shared/headers"
.main-page
  .main-page_box
    .r-content-edit
      .r-content-edit__header
        プロフィール編集
      .r-content-edit__image
        .r-content-edit__image__box
          .r-content-edit__image__box__in
            .r-content-edit__image__box__in__image
            %input{:name => "profile",class:"ll",value:@user.nickname}
      .r-content-edit__main
        %textarea{ rows: "12",cols:"78"}
        .bottom-btn
           変更する
    -# ユーザーマイページ関連のサイドバー
    = render partial: '/shared/side_bar'
-# 情報量の多いfooter
= render "shared/footer2"

app/views/users/finish.html.haml
.finished-header
  = render partial: 'layouts/user_registration_status_bar'
.finished-main
  .finished-center
    .finished-center__header
      会員登録完了
    .finished-center__main
      %p.a
        ありがとうございす。
      %p.b
        会員登録完了しました。
      = link_to root_path, {class: "mercari-atart", style: "text-decoration:none; color:white;display:block;"} do
        メルカリをはじめる
.finished-footer-view
  = render partial: 'shared/footer3'
.finished-footer
  = render partial: 'shared/footer4'

app/views/users/logout.html.haml
-# 検索窓やカテゴリーのドロップダウンメニューがあるheader
= render partial: "shared/headers"
.main-page
  .main-page_box
    .r-content
      .contents
        .logout-form
          =link_to "ログアウト", destroy_user_session_path, method: :delete
    -# ユーザーマイページ関連のサイドバー
    = render partial: '/shared/side_bar'
-# 情報量の多いfooter
= render "shared/footer2"

app/views/users/new.html.haml
= render "layouts/single_header"
.main
  .contents
    .contents__title 新規会員登録
    .regi-box
      = link_to new_user_registration_path, {class: "regi-box__btn btn__email"} do
        %i.icon__email
        = fa_icon 'envelope'
        メールアドレスで登録する
      = link_to user_facebook_omniauth_authorize_path, {method: :post, class: "regi-box__btn btn__fb"} do
        = fa_icon 'facebook-square'
        Facebookで登録する
      = link_to user_google_oauth2_omniauth_authorize_path, {method: :post, class: "regi-box__btn btn__gm"} do
        =image_tag(image_url("google-logo.png"))
        %i.icon__gm
        Googleで登録する
= render "shared/footers"

app/views/users/show.html.haml
= render partial: '/shared/headers', locals: { categories: @categories }
/////////メインページ//////
.main-page
  .main-page_box
    .r-content
      .r-content-top-main-x
        .r-content-top
          .r-content-top-main
            .top-abata
              .top-image
            .top-name
              =current_user.nickname
            .top-kazu
              .kazu1
                評価
                .kazu2
                  1
              .kazu3
                出品数
                .kazu4
                  10
        .r-content-main
          .main-top
            .main-top-left
              .main-top-left1
                お知らせ
                %ul.news-11
                  .li
                    .main-tab
                      .main-tab1
                        .tab1
                          .tab1a
                            .tab1ax
                            %img.tab1a{:alt => "", "data-src" => "//static.mercdn.net/images/mercari_profile.png", :src => "//static.mercdn.net/images/mercari_profile.png"}/
                          .tab1b
                            .tab1bx
                              WEWORKのCEOが退任疑惑。ソフトバンクなどの上からの圧力によって解任される見込み
                            .tab1d
                              .tab1dtime
                                =fa_icon "clock-o"
                              .tabspan
                                8時間前
                          .top-icon
                            =fa_icon "angle-right"
                  .li
                    .main-tab-1
                      .main-tab1-1
                        .tab1-1
                          .tab1a-1
                            .tab1ax-1
                            %img.tab1a-1{:alt => "", "data-src" => "//static.mercdn.net/images/mercari_profile.png", :src => "//static.mercdn.net/images/mercari_profile.png"}/
                          .tab1b-1
                            .tab1bx-1
                              任天堂マリオカートスマホで本日配信
                            .tab1d-1
                              .tab1dtime-1
                                =fa_icon "clock-o"
                              .tabspan-1
                                22時間前
                          .top-icon1
                            =fa_icon "angle-right"
                  .li
                    .main-tab-2
                      .main-tab1-2
                        .tab1-2
                          .tab1a-2
                            .tab1ax-2
                            %img.tab1a-2{:alt => "", "data-src" => "//static.mercdn.net/images/mercari_profile.png", :src => "//static.mercdn.net/images/mercari_profile.png"}/
                          .tab1b-2
                            .tab1bx-2
                              楽天携帯事業に参入したが、参入が遅れる見込み
                            .tab1d-2
                              .tab1dtime-2
                                =fa_icon "clock-o"
                              .tabspan-2
                                1日前
                          .top-icon2
                            =fa_icon "angle-right"
                  .li
                    .main-tab-3
                      .main-tab1-3
                        .tab1-3
                          .tab1a-3
                            .tab1ax-3
                            %img.tab1a-3{:alt => "", "data-src" => "//static.mercdn.net/images/mercari_profile.png", :src => "//static.mercdn.net/images/mercari_profile.png"}/
                          .tab1b-3
                            .tab1bx-3
                              株式会社div 10.8億円の資金調達した
                            .tab1d-3
                              .tab1dtime-3
                                =fa_icon "clock-o"
                              .tabspan-3
                                2日前
                          .top-icon3
                            =fa_icon "angle-right"
                  .li
                    .main-tab-4
                      .main-tab1-4
                        .tab1-4
                          .tab1a-4 一覧を見る
            .main-top-right
              .main-top-right1
                やることリスト
            %ul.left-box
              .li
                .main-tab-2
                  .main-tab1-2
                    .tab1-2
                      .tab1a-2
                        .tab1ax-2
                        %img.tab1a-2{:alt => "", "data-src" => "//static.mercdn.net/images/mercari_profile.png", :src => "//static.mercdn.net/images/mercari_profile.png"}/
                      .tab1b-2
                        .tab1bx-2
                          楽天携帯事業に参入したが、参入が遅れる見込み
                        .tab1d-2
                          .tab1dtime-2
                            =fa_icon "clock-o"
                          .tabspan-2
                            1日前
                      .top-icon2
                        =fa_icon "angle-right"
                          
              .main-senter-tab
                .senter-header-tab
                  購入した商品
                  .senter-content-main
                    .senter-main-top
                      .senter-main-top-left
                        .senter-main-top-left1
                          取引中
                      .senter-main-top-right
                        .senter-main-top-right1
                          過去の取引
                .senter-main-tab
                  .senter-main-tab1
                    .senter-tab1
                      .senter-tab1a
                        .senter-tab1ax
                        %img.senter-tab1a{:alt => "", "data-src" => "//static.mercdn.net/images/mercari_profile.png", :src => "//static.mercdn.net/images/mercari_profile.png"}/
                      .senter-tab1b
                        .senter-tab1bx
                          現在の取引中です。
                        .senter-tab1d
                          .senter-tab1dtime
                            =fa_icon "clock-o"
                        .senter-tabspan
                          8時間前
                      .senter-top-icon
                        =fa_icon "angle-right"
                .senter-main-tab-4
                  .senter-main-tab1-4
                    .senter-tab1-4
                      .senter-tab1a-4 一覧を見る
    = render partial: '/shared/side_bar'
.top-bottom-view
/////////////////////
//ここはフッター
.top-footer
  .top-footer__content
    %li.content__a
      メルカリについて
      %p 会社概要
      %p 採用情報
      %p プレスリリース
      %p 公式ブログ
      %p メルカリロゴ利用ガイドライン
    %li.content__b
      ヘルプ＆ガイド
      %p メルカリガイド
      %p らくらくメルカリ便
      %p ゆうゆうメルカリ便
      %p 大型メルカリ便
      %p 車体取引ガイド 
      %p メルカリあんしんあんぜん宣言！
      %p 偽ブランド品撲滅への取り組み
      %p メルカリボックス
    %li.content__c
      プライバシーと利用規約
      %p プライバシーポリシー
      %p メルカリ利用規約
      %p 安心スマホサポート制度に関<br>する利用規約
      %p コンプライアンスポリシー
    %li
      %p.content 個人データ安全管理に関わる基本<br>方針
      %p 特定商取引に関する表記
      %p 資金決済法に基づく表示
      %p 法令順守と犯罪防止のために
    %li.content__d
      国
      %p 日本
      %p United States
  .top-footer__bottom
    .top-footer__bottom__box
      %a.twitter-logo{ href:"https://twitter.com/mercari_jp"}
        
      %a.font-bottom{ href: "https://www.mercari.com/jp/"}
        %img{:src=>"https://web-jp-assets.mercdn.net/_next/static/images/logo-white-1a0696cf557ee1ed6f3c3444661d21ad.svg", :alt=>"Mercari", :class=>"top-mercari_logo"}
      .font-bottom-icon
        
      %p ©2019 Mercari

app/views/users/sms_confirmation.html.haml
= render partial: 'layouts/user_registration_status_bar'

%main.main
  %section.contents
    %h2.regi__title 電話番号の確認
    %form.regi-box
      .sms-confirmation
        .form-group
          %label 携帯電話の番号
          %input.input-default{placeholder: "携帯電話の番号の入力"}
        %p 本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
        = link_to address_user_path(current_user.id), {class: "input-default red-btn", type: "display: block;"} do
          SMSを送信する
        -# %button.input-default.red-btn SMSを送信する
        %p ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
        .right
          = link_to "#" do
            電話番号の確認が必要な理由
            = fa_icon "chevron-right"
= render partial: '/shared/footers', locals: { categories: @categories }