config/routes.rb
Rails.application.routes.draw do
  get 'user_detail/edit'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'toppages#index'
  resources :toppages, only: [:index]  do
    collection do 
      get 'search'
    end
  end
  resources :users do
    member do
      get :logout
      get :sms_confirmation
      get :address
      get :credit_card
      post :address
      post :credit_card
      get :finish
      get :credit_card_registration
    end
    resources :items, only: [:index, :new, :edit]
  end
  resources :items, except: [:index, :new, :edit] do
    resources :deals do
      collection do
        post 'purchase'
      end
    end
  end
  resources :items, except: [:index, :new, :edit]
  resources :item_images, only: [:new,:create, :destroy]
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end 
  resources :card, only: [:new, :show] do
    collection do
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/brand_group.rb
class BrandGroup < ApplicationRecord
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :brands, through: :category_brands
  has_many :category_brands
  has_many :items
  belongs_to :parent, class_name: "Category", optional: true
  has_many :categories, foreign_key: "parent_id"

end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  # dependent: :destroyによりitem消した時に一緒に消える
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images
  has_one :deal
  belongs_to :user,optional: true
  belongs_to :category,optional: true
  belongs_to :brand, optional: true
  belongs_to :region

  enum item_status: {
    "新品、未使用": "新品、未使用", 
    "未使用に近い": "未使用に近い", 
    "目立った傷や汚れなし": "目立った傷や汚れなし", 
    "やや傷や汚れあり": "やや傷や汚れあり", 
    "傷や汚れあり": "傷や汚れあり", 
    "全体的に状態が悪い": "全体的に状態が悪い", 
  }
  enum days: {
    "1〜2日で発送": "1〜2日で発送", 
    "2〜3日で発送": "2〜3日で発送", 
    "4〜7日で発送": "4〜7日で発送", 
  }
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  belongs_to :item
  mount_uploader :image, ItemimageUploader
end

app/models/region.rb
class Region < ApplicationRecord
  def index
  region_id = params[:id].to_i
  @regions = Region.all
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  has_one_attached :image
  has_one :user_detail
  has_one :card
  accepts_nested_attributes_for :user_detail
  has_many :items
  has_many :deals

  validates :nickname, presence: true, length: {maximum: 20}
  validates :password, presence: true, length: {minimum: 7, maximum: 128},  format: {with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{7,128}+\z/i}

  def self.find_auth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.nickname = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image 
      
      # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  attr_writer :family_name_kana, :first_name_kana, :family_name_kanji, :first_name_kanji

  belongs_to :user

  validates :name_kanji, presence: true, format: {with: /[^\x01-\x7E]+\s[^\x01-\x7E]+/}
  validates :name_kana, presence: true, format: {with: /[ァ-ヴ][ァ-ヴー・]+\s[ァ-ヴ][ァ-ヴー・]+/}
  validates :family_name_kana, :first_name_kana, :family_name_kanji, :first_name_kanji, presence: true

  before_validation :set_name_kana, :set_name_kanji

  def family_name_kana
    @family_name_kana
  end
  
  def first_name_kana
    @first_name_kana
  end

  def family_name_kanji
    @family_name_kanji
  end
  
  def first_name_kanji
    @first_name_kanji
  end

  def set_name_kana
    self.name_kana = [@family_name_kana, " ", @first_name_kana].join
  end

  def set_name_kanji
    self.name_kanji = [@family_name_kanji, " ", @first_name_kanji].join
  end
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :call_categories

  # require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    # Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_path(current_user.id)
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
  private
  def call_categories
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/item_images_helper.rb
module ItemImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/user_detail_helper.rb
module UserDetailHelper
end

app/views/layouts/_single_header.html.haml
%header.devise-header
  .header-contents
    .devise-header__image
      =link_to root_path do
        =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3296506464",alt:"mercari")
        -# %img{:alt => "mercari", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3296506464"}/

app/views/layouts/_user_registration_status_bar.html.haml
%header.devise-header
  .header-contents
    %h1.devise-header__image.head-logo
      =link_to root_path do
        =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3296506464",alt:"mercari")
        -# %img{:alt => "mercari", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3296506464"}/

    .nakamura-timeline
      %ol
        %li
          会員情報
          .circle
        %li
          電話番号認証
          .circle
        %li
          お届け先住所入力
          .circle
        %li
          支払い方法
          .circle
        %li
          完了
          .circle
          

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample59d
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample59d
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
  = yield
  %footer.devise-footer
    .devise-footer__box
      %ul.devise-footer__box__menu
        %li.devise-footer__box__menu__list プライバシーポリシー
        %li.devise-footer__box__menu__list メルカリ利用規約
        %li.devise-footer__box__menu__list 特定商取引に関する表記


      .devise-footer__box__img
        =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3296506464",alt:"mercari",width:"80",height: "65")
        -# %img{:alt => "mercari", :height => "65", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3296506464", :width => "80"}/
      .devise-footer__box__year
        © 2019 Mercari

app/views/shared/_breadcrumbs.html.haml
.second-header
  -case params.values_at :controller, :action
  -when ['users', 'show']
    -breadcrumb :user
  -when ['users', 'edit']
    -breadcrumb :profile
  -when ['users', 'credit_card']
    -breadcrumb :payment
  -when ['card', 'new']
    -breadcrumb :card
  -when ['user_detail', 'edit']
    -breadcrumb :registration
  -when ['users', 'logout']
    -breadcrumb :logout

  = breadcrumbs pretext: "", separator: " &rsaquo;"

app/views/shared/_footer2.html.haml
.top-bottom-view
  .top-bottom-view__left
    .top-bottom-view__left__text
      %p.text-a
        スマホで簡単フリマアプリ
      %p.text-b
        今すぐ無料ダウンロード!
      .text-c
        =image_tag("https://web-jp-assets.mercdn.net/_next/static/images/mercari_icon-f75780e32e41e052c8aaa8b446331cd8.png")
        =link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&amp;mt=8" do
          =image_tag("https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg",class:"b")
        =link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&amp;hl=ja" do
          =image_tag("https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg",class:"c")
      .text-d
    .top-bottom-view__left__image
      =image_tag("https://web-jp-assets.mercdn.net/_next/static/images/download_app_pc-a4418175e8be071827ac88d073f40e4a.png",class:"bottom-image")
/////////////////////
//ここはフッター
.top-footer
  .top-footer__content
    %li.content__a
      メルカリについて
      %p.a 会社概要
      %p 採用情報
      %p プレスリリース
      %p 公式ブログ
      %p メルカリロゴ利用ガイドライン
      =link_to root_path class:"logo" do
        = fa_icon"twitter"
      %a.logo{href: "https://www.facebook.com/mercari_jp"}
        = fa_icon"facebook-square"
    %li.content__b
      ヘルプ＆ガイド
      %p メルカリガイド
      %p らくらくメルカリ便
      %p ゆうゆうメルカリ便
      %p 大型メルカリ便
      %p 車体取引ガイド 
      %p メルカリあんしんあんぜん宣言！
      %p 偽ブランド品撲滅への取り組み
      %p メルカリボックス
    %li.content__c
      プライバシーと利用規約
      %p プライバシーポリシー
      %p メルカリ利用規約
      %p 安心スマホサポート制度に関<br>する利用規約
      %p コンプライアンスポリシー
    %li
      %p.content 個人データ安全管理に関わる基本<br>方針
      %p 特定商取引に関する表記
      %p 資金決済法に基づく表示
      %p 法令順守と犯罪防止のために
    %li.content__d
      国
      %p 日本
      %p United States
  .top-footer__bottom
    .top-footer__bottom__box
      %a.twitter-logo{ href:"https://twitter.com/mercari_jp"}
        
      %a.font-bottom{ href: "https://www.mercari.com/jp/"}
        =image_tag("https://web-jp-assets.mercdn.net/_next/static/images/logo-white-1a0696cf557ee1ed6f3c3444661d21ad.svg",alt:"Mercari", class:"top-mercari_logo")
      .font-bottom-icon
        
      %p ©2019 Mercari

app/views/shared/_footer3.html.haml
.top-bottom-view
  .top-bottom-view__left
    .top-bottom-view__left__text
      %p.text-a
        スマホで簡単フリマアプリ
      %p.text-b
        今すぐ無料ダウンロード!
      .text-c
        = image_tag("https://web-jp-assets.mercdn.net/_next/static/images/mercari_icon-f75780e32e41e052c8aaa8b446331cd8.png") 
        = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&amp;mt=8" do
          = image_tag("https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg",class:"b")
        = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&amp;hl=ja" do
          = image_tag("https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg",class:"c")
      .text-d
    .top-bottom-view__left__image
      = image_tag("https://web-jp-assets.mercdn.net/_next/static/images/download_app_pc-a4418175e8be071827ac88d073f40e4a.png",class:"bottom-image")

app/views/shared/_footer4.html.haml
.item-buypage-footer
  .item-buypage-footer__center
    %ul
      %p.text-a
        プライバシーポリシー
      %p.text-b
        メルカリ利用規約
      %p.text-c
        特定商取引に関する表記
    .image-box
      = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?2687693852",alt:"mercari",width:"80",height:"65")
    .bottom-text
      ©2019 Mercari

app/views/shared/_footers.html.haml
%footer.devise-footer
  .devise-footer__box
    %ul.devise-footer__box__menu
      %li.devise-footer__box__menu__list プライバシーポリシー
      %li.devise-footer__box__menu__list メルカリ利用規約
      %li.devise-footer__box__menu__list 特定商取引に関する表記


    .devise-footer__box__img
      =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3296506464",width: "80",alt: "mercari", height: "65")
    .devise-footer__box__year
      © 2019 Mercari

app/views/shared/_header2.html.haml
.item-buypage-header__box
  = link_to root_path, class: "merukari" do
    = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2687693852", alt:"mercari", class:"merukari")

app/views/shared/_headers.html.haml
.top-header
  .top-header__icon
    = link_to root_path, class: "btn btn-dark btn-sm" do
      = image_tag "https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg",alt:"Mercari",class:"top-header-logo"
  .top-header__box
    .top-header__box__top
    %form{:action=>"",:class=>"form"}
      -# = form_with url: toppages_path do |f|
      -#   = f.text_field :content, class: 'form__serch', placeholder: '  何かお探しですか？'
      %input{:type=>"serch",:name=>"keyword",:class =>'form__serch', :placeholder =>'  何かお探しですか？'} 
        = link_to root_path, class: "button" do
          = fa_icon "search"

.top-header__box__bottom2
  .top-header__box__bottom2__left
    .top-header__box__bottom2__left__category
      = fa_icon"list-ul"
      カテゴリーから探す
      %ul.top-header__box__bottom2__ul
        %li.lia
          - @categories.each do |category|
            - if category.parent_id == nil
              .lia-li        
                = category.name     
                %ul.second-layer
                  - @categories.each do |child|
                    - if child.parent_id == category.id
                      %li.second-menu  
                        = child.name
                        %ul.third-layer
                          - @categories.each do |baby|
                            - if baby.parent_id == child.id
                              %li.third-menu 
                                = baby.name
    .top-header__box__bottom2__left__bland
                      
      %li.bland-box  
        = link_to "#", class: "bland-text" do
          = fa_icon "tag"
          ブランドから探す
          .lic1-li  シャネル
          .lic1-li  ナイキ
          .lic1-li  ルイヴィトン
          .lic1-li  シュプリーム
          .lic1-li  アディダス
          .lic1-li  ブランド一覧
  - if user_signed_in?
    .top-header__box__bottom2__right
      .top-header__box__bottom2__right__like
        %li.like-box
          = link_to "#", class: "like-text" do
            = fa_icon"heart"
            いいね！一覧
      
      .top-header__box__bottom2__right__news
        %li.news-box
          .new-color-box
            お知らせ
            = link_to "#", class: "news-text" do
              = fa_icon "bell"
              %ul.news-lists
                .product-image
                  = image_tag ""
                .icon-right
                %li.news
                  %p.news__text
                    mikawaさんがあなたを評価しました。これで取引完了です。
                    %p.news__time
                      = fa_icon"clock-o"
                      30分前
      .top-header__box__bottom2__right__todo
        %li.todo-box
          = link_to "#", class: "todo-text" do
            = fa_icon"check"
            やることリスト
            .my-todo-box
              .my-todo-box__nothing
                現在やることリストはありません
      .top-header__box__bottom2__right__mypage
        %li.mypage-box
          .myfont-box
            .myfont-view
              = image_tag "",class:"logo"
            = link_to user_path(current_user), class: "mypage-text" do
              マイページ
            %li.mypage-mini
              .mypage-mini__header
                = image_tag "",class:"logo2"
                .mypage-mini__image
              .mypage-mini__name
                %p.mypage__mini__name__top
                  =current_user.nickname
                .hyouka
                  %p.hyouka1  評価：9
                  %p.hyouka2  出品数：9
              .money-box
                %p.money-box-1
                  売上金
                %p.money-box-2
                  ¥0
              .point-box
                %p.point-box-1
                  ポイント
                %p.point-box-2
                  P200
              .mini-mypage-bottom-top
                いいね！一覧
                .mini-mypage-bottom-top__b
                  = fa_icon "angle-right"
              .mini-mypage-bottom-bottom
                出品した商品 - 出品中
                = fa_icon "angle-right"
              .mini-mypage-bottom-bottom
                出品した商品 - 取引中
                = fa_icon "angle-right"
              .mini-mypage-bottom-bottom
                出品した商品 - 売却済み
                .mini-mypage-bottom-bottom__a
                  = fa_icon "angle-right"
              .mini-mypage-bottom-bottom
                購入した商品 - 取引中
                = fa_icon "angle-right" 
              .mini-mypage-bottom-bottom
                購入した商品 - 過去の取引
                = fa_icon "angle-right"
  - else
    .top-header__box__bottom2__right
      .top-header__box__bottom2__right__right
        = link_to new_user_path, class: "btn btn-dark btn-sm" do
          .new-user-btn
            新規会員登録
        = link_to new_user_session_path, class: "btn btn-dark btn-sm" do
          .user-login-ntn
            ログイン
-unless request.fullpath.match(/^\/$/)
  = render partial: '/shared/breadcrumbs'
.button-box
  = link_to user_signed_in? ? new_user_item_path(current_user.id) : new_user_session_path do
    %li.text 出品
    %li.camera

app/views/shared/_show_item.html.haml
.show-item__item__box
  =link_to item_path(item.id) do
    .show-item__item__box__img
      %span
        ¥#{item.price.to_s(:delimited)}
      = image_tag image_url(item.item_images[0].image.url)
    .show-item__item__box__bottom
      %span
        = item.name

app/views/shared/_side_bar.html.haml
.l-content
  .l-content-box
    .l-content-list
      = link_to user_path(current_user),class:"l-box2"do
        マイページ
        .list3
          =fa_icon "angle-right"
      = link_to "#",class:"l-box2"do
        お知らせ
        .list3
          =fa_icon "angle-right"
      = link_to "#",class:"l-box2"do
        やることリスト
        .list3
          =fa_icon "angle-right"
      = link_to "#",class:"l-box2"do
        いいね！一覧
        .list3
          =fa_icon "angle-right"
      = link_to new_user_item_path(current_user.id),class: "l-box2" do
        出品する
        .list3
          =fa_icon "angle-right"
      = link_to user_items_path(current_user.id),class: "l-box2" do
        出品した商品-出品中
        .list3
          =fa_icon "angle-right"
      = link_to "#",class:"l-box2"do
        出品した商品-取引中
        .list3
          =fa_icon "angle-right"
      = link_to "#",class:"l-box2"do
        出品した商品-売却済み
        .list3
          =fa_icon "angle-right"
      = link_to "#",class:"l-box2"do
        購入した商品-取引中
        .list3
          =fa_icon "angle-right"
      = link_to "#",class:"l-box2"do
        購入した商品-過去の取引
        .list3
          =fa_icon "angle-right"
      = link_to "#",class:"l-box2"do
        ニュース一覧
        .list3
          =fa_icon "angle-right"
      = link_to "#",class:"l-box2"do
        評価一覧
        .list3
          =fa_icon "angle-right"
      = link_to "#",class:"l-box2"do
        ガイド
        .list3
          =fa_icon "angle-right"
      = link_to "#",class:"l-box2"do
        お問い合わせ
        .list3
          =fa_icon "angle-right"
  .l-merupei-box
    メルペイ
  .l-content-box2
    = link_to "#",class:"l-box2"do
      売上・振込申請
      .list3
        =fa_icon "angle-right"
    = link_to "#",class:"l-box2"do
      ポイント
      .list3
        =fa_icon "angle-right"
  .l-settei-box
    設定
  .l-content-box3
    = link_to edit_user_path(current_user.id),class:"l-box2"do
      プロフィール
      .list3
        =fa_icon "angle-right"
    = link_to "#",class:"l-box2"do
      発送元・お届け先住所変更
      .list3
        =fa_icon "angle-right"
    =link_to credit_card_user_path(current_user),class:"l-box2" do
      支払い方法
      .list3
        =fa_icon "angle-right"
    = link_to "#",class:"l-box2"do
      メール/パスワード
      .list3
        =fa_icon "angle-right"
    = link_to user_detail_edit_path,class:"l-box2"do
      本人情報
      .list3
        =fa_icon "angle-right"
    = link_to "#",class:"l-box2"do
      電話番号
      .list3
        =fa_icon "angle-right"
    =link_to logout_user_path(current_user),class:"l-box2"do
      ログアウト
      .list3
        =fa_icon "angle-right"