config/routes.rb
Rails.application.routes.draw do
  get 'user_detail/edit'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'toppages#index'
  resources :toppages, only: [:index]  do
    collection do 
      get 'search'
    end
  end
  resources :users do
    member do
      get :logout
      get :sms_confirmation
      get :address
      get :credit_card
      post :address
      post :credit_card
      get :finish
      get :credit_card_registration
    end
    resources :items, only: [:index, :new, :edit]
  end
  resources :items, except: [:index, :new, :edit] do
    resources :deals do
      collection do
        post 'purchase'
      end
    end
  end
  resources :items, except: [:index, :new, :edit]
  resources :item_images, only: [:new,:create, :destroy]
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end 
  resources :card, only: [:new, :show] do
    collection do
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  
end

app/models/item.rb
class Item < ApplicationRecord
  # dependent: :destroyによりitem消した時に一緒に消える
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images
  has_one :deal
  belongs_to :user,optional: true
  belongs_to :category,optional: true
  belongs_to :brand, optional: true
  belongs_to :region

  enum item_status: {
    "新品、未使用": "新品、未使用", 
    "未使用に近い": "未使用に近い", 
    "目立った傷や汚れなし": "目立った傷や汚れなし", 
    "やや傷や汚れあり": "やや傷や汚れあり", 
    "傷や汚れあり": "傷や汚れあり", 
    "全体的に状態が悪い": "全体的に状態が悪い", 
  }
  enum days: {
    "1〜2日で発送": "1〜2日で発送", 
    "2〜3日で発送": "2〜3日で発送", 
    "4〜7日で発送": "4〜7日で発送", 
  }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :call_item, except: [:index, :new, :create]
  skip_before_action :authenticate_user!, only: [:show]
  
  def index
    @categories = Category.all
    @items = Item.where("user_id = #{current_user.id}")
  end

  def new
    @categories = Category.where(parent_id: nil)
    @regions = Region.all
    @item_image = ItemImage.new
    @item = Item.new
    @item.item_images.build
  end

  def create
    @item = Item.new(create_params)
    if @item.user_id == current_user.id && params.require(:item)[:item_images_attributes].present?
      if @item.save
        redirect_to root_path
        return
      else
        render_new
      end
    end
    redirect_to new_user_item_path(current_user)
  end
  
  def show
    @categories = Category.all
  end

  def edit
    @item.item_images.build
    @regions = Region.all
    @categories = Category.where(parent_id: nil)
  end

  def update
    if @item.user_id == current_user.id && params.require(:item).permit(item_images_attributes: [:image]).present?
      if @item.update(update_params)
        redirect_to root_path
        return
      else
        redirect_to edit_user_item_path(current_user)
      end
    end
  end

  def destroy
    # アイテムの削除
    if current_user.id == @item.user.id
      if @item.destroy
        redirect_to root_path
      else
        render_show
      end
    end
    
  end
  
  private
    def create_params
      params.require(:item).permit(:name,:size,:item_status,:shipping_fee,:days,:price,:explain,:region_id,:brandname,:category_id,item_images_attributes: [:image] ).merge(user_id: current_user.id)
    end
    def update_params
      params.require(:item).permit(:name,:size,:item_status,:shipping_fee,:days,:price,:explain,:region_id,:brandname,:category_id,item_images_attributes: [:image, :_destroy, :id] ).merge(user_id: current_user.id)

      # if params.require(:item).permit(item_images_attributes: [:image]).present?

      #   params.require(:item).permit(:name,:size,:item_status,:shipping_fee,:days,:price,:explain,:region_id,:brandname,:category_id,item_images_attributes: [:image] ).merge(user_id: current_user.id)
      # else
      #   return params.require(:item).permit(:name,:size,:item_status,:shipping_fee,:days,:price,:explain,:region_id,:brandname,:category_id).merge(user_id: current_user.id)
      # end
    end
    def call_item
      @item = Item.find(params[:id])
    end

    def move_to_signup
      redirect_to new_user_session_path unless user_signed_in?
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.haml
!!!
= render partial: 'shared/header2'

%script{:language => "JavaScript"}

%main.main
  .post-item-title 商品の情報を入力
  %section.contents

  = form_for @item do |f|
    .form-group-box
      %label{:for => "item_img"} 出品画像
      %span.form-require 必須
      %p 最大10枚までアップロードできます
      #drop_zone 
        - @item.item_images.each do |image|
          -if image.image.present?
            .image-box
              .image
                =image_tag(image.image.url, data: image.id)
              .bottom
                .edit
                  編集
                .delete
                  =link_to("削除", item_image_path(image.id), method: :delete) 
                  
        #text
          ドラッグ・アンドロップ
          <br>
          またはクリックしてファイルをアップロード
      %output#list
        = f.fields_for :item_images do |item_image|
          = item_image.hidden_field :id, value: item_image.object.id
          = item_image.file_field :image
      .delete_btn{height:"30px", width:"50px",color:"red"}
  

      .sell-contents
        %label{:for => "name"} 商品名
        %span.form-require 必須
        = f.text_field :name, placeholder: "商品名  (必須 40文字まで)", type: "text", value: @item.name ,class:"input-default"
        %br
        %label{:for => "explain"} 商品の説明
        %span.form-require 必須
        = f.text_area :explain, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。",size:"100×10", type: "text", value: @item.explain,class:"input-default-datail"

        %h3.each-head 商品の詳細
        %label{for: "category"} カテゴリー
        %span.form-require 必須
        %br
        
      .category_select_box
        %select.category_select{name: "category_select"}
          -@categories. each do |category|
            -if  @item.category.parent.parent.name == category.name
              %option{selected: "selected", value: category.id} #{category.name}
            -else
              %option{value: category.id} #{category.name}
        %select.category_select{name: "category_select"} 
          -@item.category.parent.parent.categories. each do |category|
            -if  @item.category.parent.name == category.name
              %option{selected: "selected",value: category.id} #{category.name}
            -else
              %option{value: category.id} #{category.name}
        %select.category_select{name: "item[category_id]"}
          -@item.category.parent.categories. each do |category|
            -if  @item.category.name == category.name
              %option{selected: "selected",value: category.id} #{category.name}
            -else
              %option{value: category.id} #{category.name}
              
      .sell-contents
      %label{for: "size"} サイズ
      %span.form-require 必須
      = f.select :size, class:"select-default", class:"jj" do
        %option{selected:"selected",value:@item.size} #{@item.size}
        %option{value: "under_xxs"} XXS以下
        %option{value: "xs_ss"} XS(SS)
        %option{value: "S"} S
        %option{value: "M"} M
        %option{value: "L"} L
        %option{value: "XL(LL)"} XL(LL)
        %option{value: "2XL(3L)"} 2XL(3L)
        %option{value: "3XL(4L)"} 3XL(4L)
        %option{value: "4XL(5L)以上"} 4XL(5L)以上
        %option{value: "FREE SIZE"} FREE SIZE

      %label{for: "brand"} ブランド
      %span.form-yourself 任意
      = f.text_field :brandname , class:"input-default",placeholder:"例）シャネル",value:@item.brandname,type: "text"
      %label{for: "item_status"} 商品の状態
      %span.form-require 必須
      = f.select :item_status do
        %option{selected:"selected",value:@item.item_status} #{@item.item_status}
        %option{value: "新品、未使用"} 新品、未使用
        %option{value: "未使用に近い"} 未使用に近い
        %option{value: "目立った傷や汚れなし"} 目立った傷や汚れなし
        %option{value: "やや傷や汚れあり"} やや傷や汚れあり
        %option{value: "傷や汚れあり"} 傷や汚れあり
        %option{value: "全体的に状態が悪い"} 全体的に状態が悪い

      %h3.each-head 配送について
      %label{for: "shippin_fee"} 配送料の負担
      %span.form-require 必須
      = f.select :shipping_fee do
        %option{selected:"selected"} #{@item.shipping_fee}
        %option{value: "送料込み(出品者負担)"} 送料込み(出品者負担)
        %option{value: "着払い(購入者負担)"} 着払い(購入者負担)


      %br
      %label{for: "from_where"} 発送元の地域
      %span.form-require 必須
      = f.select :region_id, class:"from_where"do
        %option{selected:"selected",value:@item.region.id} #{@item.region.name}
        -@regions. each do |region|
          %option{value: region.id} #{region.name}


      %br
      %label{for: "how_many_days"} 発送までの日数
      %span.form-require 必須
      = f.select :days do
        %option{selected:"selected"} #{@item.days}
        %option{value: "1〜2日で発送"} 1〜2日で発送
        %option{value: "2〜3日で発送"} 2〜3日で発送
        %option{value: "4〜7日で発送"} 4〜7日で発送

      -# %div.sell-contents
      %h3.each-head 販売価格(300〜9,999,999)
      %label{for: "price", placeholder: "例)300"} 価格
      %span.form-require 必須
      = f.text_field :price ,value: @item.price,class:"price-field"
      
      %a{:href => "/jp/help_center/getting_started/prohibited_items/", :target => "_blank"} 禁止されている出品、
      %a{:href => "/jp/help_center/getting_started/prohibited_conduct/", :target => "_blank"} 行為
      %p を必ずご確認ください。
      %p またブランド品でシリアルナンバー等がある場合はご記載ください。
      %a{:href => "/jp/help_center/getting_started/counterfeit_goods/", :target => "_blank"} 偽ブランドの販売
      %p は犯罪であり処罰される可能性があります。
      %p また、出品をもちまして
      %a{:href => "/jp/seller_terms/"} 加盟店規約
      %p に同意したことになります。

      .form-post
      = f.submit class:"form-post",value:"更新する"
    
      .form-back
        = link_to 'もどる', :back ,class:"form-back"
        -# %button.form-back もどる
= render partial: '/shared/footers', locals: { categories: @categories }

app/views/items/index.html.haml
-# 検索窓やカテゴリーのドロップダウンメニューがあるheader
= render partial: "shared/headers"
.main-page
  .main-page_box
    .r-content
      .contents
        -@items.each do |item|
          .user-item
            = link_to item_path(item.id) do
              = item.name
    -# ユーザーマイページ関連のサイドバー
    = render partial: '/shared/side_bar'
-# 情報量の多いfooter
= render "shared/footer2"

app/views/items/new.html.haml
!!!
= render partial: 'shared/header2'

%script{:language => "JavaScript"}

%main.main
  .post-item-title 商品の情報を入力
  %section.contents

  = form_for @item do |f|
    .upload-pics
      %label{:for => "item_img"} 出品画像
      %span.form-require 必須
      %p 最大10枚までアップロードできます
      #drop_zone
        = f.fields_for :item_images do |item_image|
          = item_image.label :image, {} do
            = item_image.file_field :image, {}
        %pre.drop_zone_text
          %preserve
            ドラッグアンドドロップ
            またはクリックしてファイルをアップロード
      %output#list
        -# = f.fields_for :item_images do |item_image|
          -# = item_image.file_field :image


    %div.sell-contents
      %label{:for => "name"} 商品名
      %span.form-require 必須
      = f.text_field :name, placeholder: "商品名  (必須 40文字まで)", type: "text", value: "",class:"input-default"
      %br
      %label{:for => "explain"} 商品の説明
      %span.form-require 必須
      = f.text_area :explain, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", type: "text",size:"100×10", value: "",class:"input-default-datail"

    %div.detail-to-status
      %h3.each-head 商品の詳細
      .select-form-group
        %label{for: "category"} カテゴリー
        %span.form-require 必須
        %div.category_select_box
          %select.category_select{name: "category_select"}
            %option{selected:"selected"} ---
            -@categories. each do |category|
              %option{value: category.id} #{category.name}

        %label{for: "item_status"} 商品の状態
        %span.form-require 必須
        -# = f.select :item_status, {}, {class: "select-form"} do
        = f.select :item_status, options_for_select(Item.item_statuses), {include_blank:"---"}, {class: "input-default"}

    %div.fee-to-days
      %h3.each-head 配送について
      .select-form-group
        .form__box__feedays
          %label{for: "shippin_fee"} 配送料の負担
          %span.form-require 必須
          = f.select :shipping_fee do
            %option{selected:"selected"} ---
            %option{value: "送料込み(出品者負担)"} 送料込み(出品者負担)
            %option{value: "着払い(購入者負担)"} 着払い(購入者負担)
        .shipping-box-forappend
        .form__box__feedays
          %div.form-group
            %label{for: "from_where"} 発送元の地域
            %span.form-require 必須
            = f.select :region_id, class:"from_where"do
              %option{selected:"selected"} ---
              -@regions. each do |region|
                %option{value: region.id} #{region.name}
        
        .form__box__feedays
          %div.shipping-box
            %label{for: "how_many_days"} 発送までの日数
            %span.form-require 必須
            = f.select :days, options_for_select(Item.days), {include_blank:"---"}, {class: "input-default"}

    .form-group-box2
      %h3.each-head.left-box
        販売価格(300〜9,999,999)
        %p ?
      .right-box
        .kakaku
          %ul
            %li.b
              価格
            %span.form-require 必須
          %p 
            ¥
          =f.text_field :price, placeholder: "例)300",class: "forprice",value:""
        .kakaku2
          %p
            販売手数料(10%)
          .price1    
        .kakaku3
          .p
            販売利益
          .pricebox-all

    .excuse
      %a{:href => "/jp/help_center/getting_started/prohibited_items/", :target => "_blank"} 禁止されている出品、
      %a{:href => "/jp/help_center/getting_started/prohibited_conduct/", :target => "_blank"} 行為
      %span を必ずご確認ください。
      %span またブランド品でシリアルナンバー等がある場合はご記載ください。
      %a{:href => "/jp/help_center/getting_started/counterfeit_goods/", :target => "_blank"} 偽ブランドの販売
      %span は犯罪であり処罰される可能性があります。
      %span また、出品をもちまして
      %a{:href => "/jp/seller_terms/"} 加盟店規約
      %span に同意したことになります。

      .form-post
        = f.submit class:"form-post",value:"出品する"
    
      .form-back
        = link_to 'もどる', :back ,class:"form-back"
= render partial: '/shared/footers', locals: { categories: @categories }

app/views/items/show.html.haml
.shyouhin-main
  = render partial: '/shared/headers'
  //////////商品の説明/////////////
  .shyouhin-box
    .item-name
      #{@item.name}

    .item-main-content

      .item-photo
        .item-photo-main
          -@item.item_images.each do |image|
            .item-photo-main__image
              = image_tag image.image.url

        .photo-slide
          -@item.item_images.each do |image|
            = image_tag image.image.url

      %table.item-category
        %th.user-name
          出品者
        %th.user-name-review
          = link_to "#" do
            =@item.user.nickname
            .face
              .smile
                = fa_icon "smile-o"
                413
              .usual
                = fa_icon "meh-o"
                40
              .tired
                = fa_icon "frown-o"
                1
          %tr
            %td.user-name
              カテゴリー
            %td.parent-parent-name
              = link_to "#", class:"hover9" do
                = @item.category.parent.parent.name
                = fa_icon "angle-right"
              = link_to "#", class:"hover9" do
                = @item.category.parent.name
                = fa_icon "angle-right"
              = link_to "#", class:"hover9" do 
                = @item.category.name
          %tr
            %th.brand-to-days
              ブランド
            %th.rightside-brand-to-days
              = @item.brandname
          %tr
            %th.brand-to-days
              商品状態
            %th.rightside-brand-to-days
              =@item.item_status
          %tr
            %th.brand-to-days
              配送料の負担
            %th.rightside-brand-to-days
              = @item.shipping_fee
          %tr
            %th.brand-to-days
              配送方法
            %th.rightside-brand-to-days
              = @item.shipping_way
          %tr
            %th.brand-to-days
              発送元地域
            %th.rightside-brand-to-days
              = link_to "#" do
                %option{value: @item.id} #{@item.region.name}
          %tr
            %th.brand-to-days
              発送日の目安
            %th.rightside-brand-to-days
              %option{value: @item.id} #{@item.days}

    .item-price
      .price-name
        ¥ #{@item.price.to_s(:delimited)}
      .price-tax
        (税込)
      .price-free
        送料込み
    -unless user_signed_in? && current_user.id == @item.user.id
      -if @item.deal.present?
        .item-sold
          この商品は売り切れました。
      -else
        .item-buy
          = link_to new_item_deal_path(@item.id) do
            購入画面に進む
    .item-setumei
      %p{value: @item.id} #{@item.explain}
    .item-hyouka
      .item-hyouka-left
        .item-iine
          .hyouka-hato
            = fa_icon "heart-o"
          .hyouka-iine
            いいね
          .hyouka-kazu
            10
        .item-iine-1
          .hyouka-hata
            = fa_icon "flag-o" 
          .item-houkoku
            不適切な商品の報告
      .item-hyouka-right
        .item-icon
          =fa_icon "lock"
        .item-span
          = link_to "#", class:"hover8" do
            あんしん・あんぜんへの取り組み
        /////////////コメント欄//////////////////////////
  -if user_signed_in? && current_user.id == @item.user.id
    .item-message
      .message-box
        .message-box-content
          = link_to edit_user_item_path(current_user.id, @item.id), class: "input-default btn red" do
            商品の編集
          %p or
          = audio_tag("coin2.mp3",id:"audio")
          %button.input-default.audioButton.btn.grey#item-delete-modal-on 商品の削除
          = javascript_tag do
            document.querySelector('.audioButton').onclick = function () {
            document.querySelector("#audio").play();
            Materialize.toast("You Answered", 4000,'rounded')
            }
        .modal#item-delete-modal
          .modal-banner
            .modal-banner__body
              .modal-title
                確認
              削除すると二度と復活できません。<br>削除する代わりに停止することもできます。<br><br>本当に削除しますか？
            .modal-banner__bottom
              %a.modal-button
                キャンセル
              =link_to item_path(@item.id), method: :delete, class: "modal-button" do
                削除する
  .item-message
    .message-box
      .message-box-content
        .message-form
          .message-setumei
            相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
          .message-text
          .message-coment
            .message-coment-text
              コメントする
              /////////////ソーシャルメデイアログイン///////////////////
  -unless user_signed_in? && current_user.id == @item.user.id
    .item-link
      .link-left
        .link-icon
          = fa_icon "angle-left"
        .link-box
          = link_to "#", class:"hover9" do
            Amazon
      .link-right
        .link-icon-1
          = fa_icon "angle-right"
        .link-box-1
          = link_to "#", class:"hover9" do
            Google
    .item-media
      .media-top
        .social-left
          = fa_icon "facebook-official"
        .social-center
          = fa_icon "twitter-square"
        .social-right
          = fa_icon "pinterest-square"

          /////////////その他の出品////////////////////////
    .item-user-profile
      = link_to "#", class:"hover9" do
        =@item.user.nickname
        %p のその他の出品
      .user-item-content
        .user-item-box
          -@item.user.items.each_with_index do |item, index|
            -if (index+1)%3 == 0
              .items-box-3
                .items-img-3
                  = image_tag item.item_images[0].image.url
                .items-text-3
                  .items-text-name-3
                    = item.name
                  .items-text-name1-3
                    .items-text-price-3
                      ¥2,000,000
                    .items-math-3
                      = fa_icon "heart-o"
                      1
            -else
              .items-box
                .items-img
                  = image_tag item.item_images[0].image.url
                .items-text
                  .items-text-name
                    = item.name
                  .items-text-name1
                    .items-text-price
                      ¥2,000,000
                    .items-math
                      = fa_icon "heart-o"
                      1
            -if index == 5
              -break
            //////////////そのほかの出品パート２////////////////////////

      .item-user-profile
        = link_to "#", class:"hover9" do
          同じカテゴリーのその他の出品
      .user-item-content
        .user-item-box
          -@item.user.items.each_with_index do |item, index|
            -if (index+1)%3 == 0
              .items-box-3
                .items-img-3
                  = image_tag item.item_images[0].image.url
                .items-text-3
                  .items-text-name-3
                    = item.name
                  .items-text-name1-3
                    .items-text-price-3
                      ¥2,000,000
                    .items-math-3
                      = fa_icon "heart-o"
                      1
            -else
              .items-box
                .items-img
                  = image_tag item.item_images[0].image.url
                .items-text
                  .items-text-name
                    = item.name
                  .items-text-name1
                    .items-text-price
                      ¥2,000,000
                    .items-math
                      = fa_icon "heart-o"
                      1

            -if index == 5
              -break

  ///////////詳細のフッター////////////////////////

  .item-second-footer
    .item-footer-main
      .item-footer-name
        メルカリ
        .item-footer-icon
          = fa_icon "angle-right"
.item-footer-syousai
  = render partial: '/shared/footer2'