config/routes.rb
Rails.application.routes.draw do
  get 'user_detail/edit'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'toppages#index'
  resources :toppages, only: [:index]  do
    collection do 
      get 'search'
    end
  end
  resources :users do
    member do
      get :logout
      get :sms_confirmation
      get :address
      get :credit_card
      post :address
      post :credit_card
      get :finish
      get :credit_card_registration
    end
    resources :items, only: [:index, :new, :edit]
  end
  resources :items, except: [:index, :new, :edit] do
    resources :deals do
      collection do
        post 'purchase'
      end
    end
  end
  resources :items, except: [:index, :new, :edit]
  resources :item_images, only: [:new,:create, :destroy]
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end 
  resources :card, only: [:new, :show] do
    collection do
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :call_categories

  # require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    # Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_path(current_user.id)
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
  private
  def call_categories
    @categories = Category.all
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/new.html.haml
= render partial: "shared/headers"
.main-page
  .main-page_box
    .r-content
      .card-title
        クレジットカード情報入力
      .contents-card
        .formm-group.card-number
          = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
            .form-group
              %label カード番号
              = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            .form-group.card-number
              .card-images
                = image_tag(image_url('visa.png'))
                = image_tag(image_url('mastercard.png'))
                = image_tag(image_url('saisoncard.png'))
                = image_tag(image_url('jcb.png'))
                = image_tag(image_url('americanexpress.png'))
                = image_tag(image_url('dinersclub.png'))
                = image_tag(image_url('discover.png'))
            .form-group.card-number
              %label 有効期限
              %select#exp_month{name: "exp_month", type: "text"}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %span 月/
              %select#exp_year{name: "exp_year", type: "text"}
                %option{value: ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %span 年
            .form-group.card-number
              %label セキュリティコード
              = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
              #card_token
              = audio_tag("trumpet1 (4).mp3",id:"audio")
              = submit_tag "追加する" ,class:"botan audioButton",id: "token_submit"
              = javascript_tag do
                document.querySelector('.audioButton').onclick = function () {
                document.querySelector("#audio").play();
                Materialize.toast("You Answered", 4000,'rounded')
                }
    = render partial: '/shared/side_bar'
= render "shared/footer2"

app/views/card/origin_new.html.haml
= render partial: "shared/headers"
.main-page
  .main-page_box
    .r-content
      .card-title
        クレジットカード情報入力
      .contents-card
        .form-group.card-number
          = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
            %label カード番号
            %span.form-require 必須
            %br
            = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            %br
            .form-group
              .card-images
                = image_tag(image_url('visa.png'))
                = image_tag(image_url('mastercard.png'))
                = image_tag(image_url('saisoncard.png'))
                = image_tag(image_url('jcb.png'))
                = image_tag(image_url('americanexpress.png'))
                = image_tag(image_url('dinersclub.png'))
                = image_tag(image_url('discover.png'))
        .form-group.card-number
          %label 有効期限
          %span.form-require 必須
          %br
          %select#exp_month{name: "exp_month", type: "text"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          %span 月/
          %select#exp_year{name: "exp_year", type: "text"}
            %option{value: ""} --
            %option{value: "2019"}19
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
          %span 年
          %br
        .form-group.card-number
          %label セキュリティコード
          %span.form-require 必須
          %br
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
        .form-group.card-number
          = submit_tag "追加する",id: "token_submit"
    = render partial: '/shared/side_bar'
= render "shared/footer2"

app/views/card/show.html.haml
= render partial: "shared/headers"
.main-page
  .main-page_box
    .r-content
      .card-title
        支払い方法
      .contents-card-show
        .card-top-title
          %label クレジットカード一覧
        .card-show
          = "**** **** **** " + @default_card_information.last4
          %br
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
          .card-form-group
            = form_tag( delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
              %input{ type: "hidden", calss:"card-form-group", name: "card_id", value: "" } 
              %button 削除する
    = render partial: '/shared/side_bar'
= render "shared/footer2"